//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Form.ProdutoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produto", Namespace="http://schemas.datacontract.org/2004/07/WCF_Exemplo.DataContracts")]
    [System.SerializableAttribute()]
    public partial class Produto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Preco {
            get {
                return this.PrecoField;
            }
            set {
                if ((this.PrecoField.Equals(value) != true)) {
                    this.PrecoField = value;
                    this.RaisePropertyChanged("Preco");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProdutoService.IProdutoService")]
    public interface IProdutoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/Create", ReplyAction="http://tempuri.org/IProdutoService/CreateResponse")]
        WCF_Form.ProdutoService.CreateResponse Create(WCF_Form.ProdutoService.CreateRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/Create", ReplyAction="http://tempuri.org/IProdutoService/CreateResponse")]
        System.Threading.Tasks.Task<WCF_Form.ProdutoService.CreateResponse> CreateAsync(WCF_Form.ProdutoService.CreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/Edit", ReplyAction="http://tempuri.org/IProdutoService/EditResponse")]
        WCF_Form.ProdutoService.EditResponse Edit(WCF_Form.ProdutoService.EditRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/Edit", ReplyAction="http://tempuri.org/IProdutoService/EditResponse")]
        System.Threading.Tasks.Task<WCF_Form.ProdutoService.EditResponse> EditAsync(WCF_Form.ProdutoService.EditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/Delete", ReplyAction="http://tempuri.org/IProdutoService/DeleteResponse")]
        WCF_Form.ProdutoService.DeleteResponse Delete(WCF_Form.ProdutoService.DeleteRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/Delete", ReplyAction="http://tempuri.org/IProdutoService/DeleteResponse")]
        System.Threading.Tasks.Task<WCF_Form.ProdutoService.DeleteResponse> DeleteAsync(WCF_Form.ProdutoService.DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/Get", ReplyAction="http://tempuri.org/IProdutoService/GetResponse")]
        WCF_Form.ProdutoService.GetResponse Get(WCF_Form.ProdutoService.GetRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/Get", ReplyAction="http://tempuri.org/IProdutoService/GetResponse")]
        System.Threading.Tasks.Task<WCF_Form.ProdutoService.GetResponse> GetAsync(WCF_Form.ProdutoService.GetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/Find", ReplyAction="http://tempuri.org/IProdutoService/FindResponse")]
        WCF_Form.ProdutoService.FindResponse Find(WCF_Form.ProdutoService.FindRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/Find", ReplyAction="http://tempuri.org/IProdutoService/FindResponse")]
        System.Threading.Tasks.Task<WCF_Form.ProdutoService.FindResponse> FindAsync(WCF_Form.ProdutoService.FindRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nome;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string marca;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public decimal preco;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string mensagem;
        
        public CreateRequest() {
        }
        
        public CreateRequest(string nome, string marca, decimal preco, string mensagem) {
            this.nome = nome;
            this.marca = marca;
            this.preco = preco;
            this.mensagem = mensagem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CreateResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string mensagem;
        
        public CreateResponse() {
        }
        
        public CreateResponse(bool CreateResult, string mensagem) {
            this.CreateResult = CreateResult;
            this.mensagem = mensagem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Edit", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EditRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WCF_Form.ProdutoService.Produto produto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string mensagem;
        
        public EditRequest() {
        }
        
        public EditRequest(WCF_Form.ProdutoService.Produto produto, string mensagem) {
            this.produto = produto;
            this.mensagem = mensagem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EditResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EditResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool EditResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string mensagem;
        
        public EditResponse() {
        }
        
        public EditResponse(bool EditResult, string mensagem) {
            this.EditResult = EditResult;
            this.mensagem = mensagem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string mensagem;
        
        public DeleteRequest() {
        }
        
        public DeleteRequest(int id, string mensagem) {
            this.id = id;
            this.mensagem = mensagem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool DeleteResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string mensagem;
        
        public DeleteResponse() {
        }
        
        public DeleteResponse(bool DeleteResult, string mensagem) {
            this.DeleteResult = DeleteResult;
            this.mensagem = mensagem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Get", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string mensagem;
        
        public GetRequest() {
        }
        
        public GetRequest(int id, string mensagem) {
            this.id = id;
            this.mensagem = mensagem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WCF_Form.ProdutoService.Produto GetResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string mensagem;
        
        public GetResponse() {
        }
        
        public GetResponse(WCF_Form.ProdutoService.Produto GetResult, string mensagem) {
            this.GetResult = GetResult;
            this.mensagem = mensagem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Find", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string mensagem;
        
        public FindRequest() {
        }
        
        public FindRequest(string mensagem) {
            this.mensagem = mensagem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WCF_Form.ProdutoService.Produto[] FindResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string mensagem;
        
        public FindResponse() {
        }
        
        public FindResponse(WCF_Form.ProdutoService.Produto[] FindResult, string mensagem) {
            this.FindResult = FindResult;
            this.mensagem = mensagem;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProdutoServiceChannel : WCF_Form.ProdutoService.IProdutoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProdutoServiceClient : System.ServiceModel.ClientBase<WCF_Form.ProdutoService.IProdutoService>, WCF_Form.ProdutoService.IProdutoService {
        
        public ProdutoServiceClient() {
        }
        
        public ProdutoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProdutoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCF_Form.ProdutoService.CreateResponse WCF_Form.ProdutoService.IProdutoService.Create(WCF_Form.ProdutoService.CreateRequest request) {
            return base.Channel.Create(request);
        }
        
        public bool Create(string nome, string marca, decimal preco, ref string mensagem) {
            WCF_Form.ProdutoService.CreateRequest inValue = new WCF_Form.ProdutoService.CreateRequest();
            inValue.nome = nome;
            inValue.marca = marca;
            inValue.preco = preco;
            inValue.mensagem = mensagem;
            WCF_Form.ProdutoService.CreateResponse retVal = ((WCF_Form.ProdutoService.IProdutoService)(this)).Create(inValue);
            mensagem = retVal.mensagem;
            return retVal.CreateResult;
        }
        
        public System.Threading.Tasks.Task<WCF_Form.ProdutoService.CreateResponse> CreateAsync(WCF_Form.ProdutoService.CreateRequest request) {
            return base.Channel.CreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCF_Form.ProdutoService.EditResponse WCF_Form.ProdutoService.IProdutoService.Edit(WCF_Form.ProdutoService.EditRequest request) {
            return base.Channel.Edit(request);
        }
        
        public bool Edit(WCF_Form.ProdutoService.Produto produto, ref string mensagem) {
            WCF_Form.ProdutoService.EditRequest inValue = new WCF_Form.ProdutoService.EditRequest();
            inValue.produto = produto;
            inValue.mensagem = mensagem;
            WCF_Form.ProdutoService.EditResponse retVal = ((WCF_Form.ProdutoService.IProdutoService)(this)).Edit(inValue);
            mensagem = retVal.mensagem;
            return retVal.EditResult;
        }
        
        public System.Threading.Tasks.Task<WCF_Form.ProdutoService.EditResponse> EditAsync(WCF_Form.ProdutoService.EditRequest request) {
            return base.Channel.EditAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCF_Form.ProdutoService.DeleteResponse WCF_Form.ProdutoService.IProdutoService.Delete(WCF_Form.ProdutoService.DeleteRequest request) {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(int id, ref string mensagem) {
            WCF_Form.ProdutoService.DeleteRequest inValue = new WCF_Form.ProdutoService.DeleteRequest();
            inValue.id = id;
            inValue.mensagem = mensagem;
            WCF_Form.ProdutoService.DeleteResponse retVal = ((WCF_Form.ProdutoService.IProdutoService)(this)).Delete(inValue);
            mensagem = retVal.mensagem;
            return retVal.DeleteResult;
        }
        
        public System.Threading.Tasks.Task<WCF_Form.ProdutoService.DeleteResponse> DeleteAsync(WCF_Form.ProdutoService.DeleteRequest request) {
            return base.Channel.DeleteAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCF_Form.ProdutoService.GetResponse WCF_Form.ProdutoService.IProdutoService.Get(WCF_Form.ProdutoService.GetRequest request) {
            return base.Channel.Get(request);
        }
        
        public WCF_Form.ProdutoService.Produto Get(int id, ref string mensagem) {
            WCF_Form.ProdutoService.GetRequest inValue = new WCF_Form.ProdutoService.GetRequest();
            inValue.id = id;
            inValue.mensagem = mensagem;
            WCF_Form.ProdutoService.GetResponse retVal = ((WCF_Form.ProdutoService.IProdutoService)(this)).Get(inValue);
            mensagem = retVal.mensagem;
            return retVal.GetResult;
        }
        
        public System.Threading.Tasks.Task<WCF_Form.ProdutoService.GetResponse> GetAsync(WCF_Form.ProdutoService.GetRequest request) {
            return base.Channel.GetAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCF_Form.ProdutoService.FindResponse WCF_Form.ProdutoService.IProdutoService.Find(WCF_Form.ProdutoService.FindRequest request) {
            return base.Channel.Find(request);
        }
        
        public WCF_Form.ProdutoService.Produto[] Find(ref string mensagem) {
            WCF_Form.ProdutoService.FindRequest inValue = new WCF_Form.ProdutoService.FindRequest();
            inValue.mensagem = mensagem;
            WCF_Form.ProdutoService.FindResponse retVal = ((WCF_Form.ProdutoService.IProdutoService)(this)).Find(inValue);
            mensagem = retVal.mensagem;
            return retVal.FindResult;
        }
        
        public System.Threading.Tasks.Task<WCF_Form.ProdutoService.FindResponse> FindAsync(WCF_Form.ProdutoService.FindRequest request) {
            return base.Channel.FindAsync(request);
        }
    }
}
